In [59]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy
import seaborn as sns
from sklearn import metrics
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

In [27]:
df = pd.read_csv('data/VoiceQuality.csv')

In [28]:
df.head()

Unnamed: 0 Operator IndoorOutdoorTravelling NetworkType  Rating  \
0           0   Airtel                  Indoor          3G       5   
1           1     RJio                  Indoor          4G       4   
2           2   Airtel                 Outdoor          3G       5   
3           3   Airtel              Travelling          3G       5   
4           4     RJio                  Indoor          4G       5   

  CallDropCategory   Latitude  Longitude   StateName  
0     Satisfactory  28.422966  76.912324     Haryana  
1     Satisfactory  11.158358  77.301897  Tamil Nadu  
2     Satisfactory  28.422931  76.912253     Haryana  
3     Satisfactory  28.422947  76.912260     Haryana  
4     Satisfactory  25.625990  85.094294       Bihar

In [29]:
df.IndoorOutdoorTravelling.unique()

array(['Indoor', 'Outdoor', 'Travelling'], dtype=object)

In [30]:
df.IndoorOutdoorTravelling.replace('Travelling', 'Outdoor', inplace=True)

In [31]:
df.IndoorOutdoorTravelling.unique()

array(['Indoor', 'Outdoor'], dtype=object)

In [32]:
df['IndoorOutdoorTravelling'] =  df['IndoorOutdoorTravelling'].map({'Indoor':1, 'Outdoor':0}).astype(int)

In [33]:
df.IndoorOutdoorTravelling.unique()

array([1, 0], dtype=int64)

In [34]:
df.head()

Unnamed: 0 Operator  IndoorOutdoorTravelling NetworkType  Rating  \
0           0   Airtel                        1          3G       5   
1           1     RJio                        1          4G       4   
2           2   Airtel                        0          3G       5   
3           3   Airtel                        0          3G       5   
4           4     RJio                        1          4G       5   

  CallDropCategory   Latitude  Longitude   StateName  
0     Satisfactory  28.422966  76.912324     Haryana  
1     Satisfactory  11.158358  77.301897  Tamil Nadu  
2     Satisfactory  28.422931  76.912253     Haryana  
3     Satisfactory  28.422947  76.912260     Haryana  
4     Satisfactory  25.625990  85.094294       Bihar

In [35]:
encoder = LabelEncoder()

In [36]:
df['CallQuality'] = encoder.fit_transform(df.CallDropCategory)

In [45]:
df.head()

Unnamed: 0 Operator  IndoorOutdoorTravelling NetworkType  Rating  \
0           0   Airtel                        1          3G       5   
1           1     RJio                        1          4G       4   
2           2   Airtel                        0          3G       5   
3           3   Airtel                        0          3G       5   
4           4     RJio                        1          4G       5   

  CallDropCategory   Latitude  Longitude   StateName  CallQuality  
0     Satisfactory  28.422966  76.912324     Haryana            3  
1     Satisfactory  11.158358  77.301897  Tamil Nadu            3  
2     Satisfactory  28.422931  76.912253     Haryana            3  
3     Satisfactory  28.422947  76.912260     Haryana            3  
4     Satisfactory  25.625990  85.094294       Bihar            3

In [26]:
# 0 = Call dropped
# 1 = Poor Network
# 2 = 
# 3 = Satisfactory
df.CallDropCategory.unique() 

array([3, 1, 0, 2], dtype=int64)

In [46]:
df['Network'] = encoder.fit_transform(df.NetworkType)
#0 = 2G
#1 = 3G
#2 = 4G

In [51]:
df.head()

Unnamed: 0 Operator  IndoorOutdoorTravelling NetworkType  Rating  \
0           0   Airtel                        1          3G       5   
1           1     RJio                        1          4G       4   
2           2   Airtel                        0          3G       5   
3           3   Airtel                        0          3G       5   
4           4     RJio                        1          4G       5   

  CallDropCategory   Latitude  Longitude   StateName  CallQuality  Network  
0     Satisfactory  28.422966  76.912324     Haryana            3        1  
1     Satisfactory  11.158358  77.301897  Tamil Nadu            3        2  
2     Satisfactory  28.422931  76.912253     Haryana            3        1  
3     Satisfactory  28.422947  76.912260     Haryana            3        1  
4     Satisfactory  25.625990  85.094294       Bihar            3        2

In [56]:
X = df[['IndoorOutdoorTravelling', 'Rating', 'Latitude', 'Longitude', 'Network']]
y = df['CallQuality']

In [57]:
X.head()

IndoorOutdoorTravelling  Rating   Latitude  Longitude  Network
0                        1       5  28.422966  76.912324        1
1                        1       4  11.158358  77.301897        2
2                        0       5  28.422931  76.912253        1
3                        0       5  28.422947  76.912260        1
4                        1       5  25.625990  85.094294        2

In [92]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state = 42)

In [93]:
Model = KNeighborsClassifier(n_neighbors=5)

In [94]:
Model.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [95]:
prediction = Model.predict(X_test)

In [96]:
metrics.accuracy_score(y_test, prediction)

0.8368780797965347

In [97]:
print(metrics.confusion_matrix(y_test, prediction))
print(metrics.classification_report(y_test, prediction))

[[ 1279   758   215   175]
 [  649  2250   368   500]
 [  347   692  1109   352]
 [  224   614   237 21686]]
             precision    recall  f1-score   support

          0       0.51      0.53      0.52      2427
          1       0.52      0.60      0.56      3767
          2       0.57      0.44      0.50      2500
          3       0.95      0.95      0.95     22761

avg / total       0.84      0.84      0.84     31455



In [81]:
model1 = KNeighborsClassifier?

In [ ]:
model1 = KNeighborsClassifier

In [ ]:
model1 = KNeighborsClassifier